import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {configureContainer, setLifecycleAdapter} from '../../../src';
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

configureContainer({
    debug: import.meta.env.DEV,
    baseDisposalDelay: 10_000,
    hotDisposalDelay: 30_000,
    veryHotDisposalDelay: 60_000,
    maxEntries: 50,
    hotThreshold: 7,
    veryHotThreshold: 15,
});

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <nav className="flex items-center justify-center gap-6 py-4 border-b border-zinc-200 dark:border-zinc-800">
            <a href="/" className="hover:underline">Home</a>
            <a href="/pages/currencies" className="hover:underline">Currencies</a>
            <a href="/pages/markets" className="hover:underline">Markets</a>
        </nav>
        {children}</body>
        </html>
    );
}
